on: [push]
name: ARMActionSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: azure/login@v1
        
        env:
           creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/arm-deploy@v1
        id: deploy
        with:
         resourceGroupName: Bhoomika-Rg
         templateLocation: B899806/test_github/stg.json
         deploymentName: newestt
