on: [push]
name: ARMActionSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: azure-arm-action@main
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resourceGroupName: Bhoomika-rg
        templateLocation: B899806/test_github/stg.json
        
