on: [push]
name: AzureARMSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true
    - uses: azure/arm-deploy@v1
      with:
        subscriptionId: "50b51095-fe96-401c-9d4f-693cf6486f39"
        resourceGroupName: Bhoomika-Rg
        template: ./stg.json
        
        
