on: [push]
name: AzureARMSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
        "clientId": "9f67f27f-9c96-4f71-a384-fa6acd6f0648"
        "subscriptionId": "50b51095-fe96-401c-9d4f-693cf6486f39"
        "tenantId": "ab8614a3-38fa-4410-81cc-2cff09afdee1"

    - run: |
        az group deployment create -n github-dev --aux-subs 50b51095-fe96-401c-9d4f-693cf6486f39 -g Bhoomika-Rg --template-file stg.json
   
