on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
   
    - name:  deploy databricks 
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: infra/bicep/db.bicep
        parameters: infra/bicep/main.bicep

    - name:  deploy eventhub 
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra/bicep/eventhub.bicep 
        parameters: ./infra/bicep/main.bicep
      
    - name:  deploy keyvault 
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra/bicep/kv.bicep
        parameters: ./infra/bicep/main.bicep
   
    - name:  deploy functionapp 
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra/bicep/appfunction.bicep
        parameters: ./infra/bicep/main.bicep
        
       
   
        
    
    - name: deploy storage 
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra/bicep/stg.bicep
        parameters: ./infra/bicep/main.bicep
        
        
        
    - name:  deploy eventhub 
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra/json/bhoom-evenhub.json
        parameters: ./infra/json/eventhubparam.json

    - name:  deploy databricks 
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra/json/bhoom-dbicks.json
        parameters: ./infra/json/databricksparamnew.json

   
    - name:  deploy keyvault 
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra/json/keyvault.json
        parameters: ./infra/json/keyvaultparam.json
        
    - name:  deploy Functionapp 
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra/json/bhoom-fapp.json
        parameters: ./infra/json/funappparam.json
