name: Build and deploy dotnet core app to Azure Function App - allsec-bicep-eus2

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'functionapp' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output function.zip
          popd

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: eventfunction
          path: ./functionapp
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: eventfunction
          path: './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          
      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'allsec-bicep-eus2'
          #slot-name: 'functiondeploy'
          package: './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/function.zip'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_d9eaf3989c05416bafa1c4db542bf4b5 }}
