name: .NET Function build from sln
on:
  workflow_dispatch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main
    
    - name: Setup .NET
      uses: actions/checkout@main
      with:
        dotnet-version: 5.0.x
        path: ./functionapp

    # dotnet build and publish
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o ./eventhubfunction/function.zip
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
          name: eventfunction
          path: ./functionapp/function.zip
          
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
          name: eventfunction
          path: ../functionapp
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'bicep-func-qvjpsokjsb7hs'
        slot-name: 'production'
        package: './eventhubfunction/function.zip'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_392c7418368b4607a07b44469dc2d1f2 }}

